### ISSUE TITLE
Telnet.c Authentication failure

### ISSUE THREAD

**Issue by ravi-numato** [x893/Microchip#1]
In telnet.c if we tried to login using **TeraTerm,** **Putty** , Its unable to authenticate. At line no. 245, its always satisfy the 'if condition' and its never goes in the 'SM_GET_PASSWORD' state.
**But it is working fine with Hyperterminal.**

**Comment by x893** [comment]
Check with latest TCP/IP stack from Microchip.
http://www.microchip.com/mplab/microchip-libraries-for-applications
